// <auto-generated />
using System;
using LounasRavintola.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LounasRavintola.Migrations.WeekMenu
{
    [DbContext(typeof(WeekMenuContext))]
    partial class WeekMenuContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("LounasRavintola.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("G")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("L")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<bool>("V")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekDay")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekMenuForeignKey")
                        .HasColumnType("INTEGER");

                    b.HasKey("MenuItemId");

                    b.HasIndex("WeekMenuForeignKey");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("LounasRavintola.Models.WeekMenu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("WeekMenus");
                });

            modelBuilder.Entity("LounasRavintola.Models.MenuItem", b =>
                {
                    b.HasOne("LounasRavintola.Models.WeekMenu", "WeekMenu")
                        .WithMany("MenuItems")
                        .HasForeignKey("WeekMenuForeignKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WeekMenu");
                });

            modelBuilder.Entity("LounasRavintola.Models.WeekMenu", b =>
                {
                    b.Navigation("MenuItems");
                });
#pragma warning restore 612, 618
        }
    }
}
